### ISSUE TITLE
earthquake data time column is clobbered

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/data-services#101]
it seems that the time column is zeroed for the earthquake data in common data
![screenshot 2014-11-12 18 02 36](https://cloud.githubusercontent.com/assets/1041056/5020392/b7169e16-6a96-11e4-8591-ba6634522e62.png)

**Comment by rafatower** [comment]
The problem is that SHP format does not support datetimes/timestamps. It encodes dates in `YYYYMMDD` format. Looking for a workaround...
