### ISSUE TITLE
Built in georeferencer does not georeference some multi-word or hyphenated cities

### ISSUE THREAD

**Issue by namessanti** [CartoDB/data-services#111]
Specifically, Hong Kong and Marne-la-Vallée, France recently, but I have experienced this in the past with other locations

**Comment by iriberri** [comment]
This is due to the normalization of those names, @juanignaciosl will take care of this here https://github.com/CartoDB/data-services/issues/30

**Comment by iriberri** [comment]
Will take care of this in another issue.
