### ISSUE TITLE
Add DMA data

### ISSUE THREAD

**Issue by saleiva** [CartoDB/data-services#118]
http://geocommons.com/overlays/106797

**Comment by iriberri** [comment]
![image](https://cloud.githubusercontent.com/assets/1730320/6228112/260aa31e-b6a8-11e4-8741-54710eccaf9a.png)

**Comment by saleiva** [comment]
I'm not sure if we should research a bit on this and find the best data source... what do you think?

**Comment by iriberri** [comment]
Sure. Taking a look at it.

**Comment by iriberri** [comment]
The DMA boundaries and DMA data are owned solely and exclusively by The Nielsen Company. Any use and or reproduction of these materials without the express written consent of The Nielsen Company is strictly prohibited.
