### ISSUE TITLE
Fix Spanish Admin 1 errors

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/data-services#12]
Steps to reproduce

Import the attached dataset (contains spanish admin 1 names, or Autonomous communities http://en.wikipedia.org/wiki/Autonomous_communities_of_Spain)
Geocode by administrative regions using the "procedencia" column.

Expected

It should identify most or all the records of the table

Actual

Our geocoder identifies just 9 records.

**Comment by iriberri** [comment]
Both autonomous comms and provinces are working for Spain atm.
