### ISSUE TITLE
Some USA Zipcodes don't Geocode

### ISSUE THREAD

**Issue by sylsoft** [CartoDB/data-services#120]
Loaded 583 records, 19 didn't Geocode (by zipcode, not address). Due to multiple records from the same University, the 19 records that didn't Geocode were from the following 10 zipcodes:
04420
06459
06723
1570 5 
16541
17405
18440
18711
18766
45501
I checked each of the above codes on the US Post Office website here, all were valid: 
https://tools.usps.com/go/ZipLookupAction_input
Thanks

**Comment by iriberri** [comment]
We are currently offering US Census ZCTAs, so despite of the fact that the zipcodes really exist, we don't have ZCTA areas for them in our database.
