### ISSUE TITLE
Input strings should be trimmed before passed to geocoder

### ISSUE THREAD

**Issue by rafatower** [CartoDB/data-services#126]
We've received a number of support requests because of leading/trailing whitespaces/tabs preventing a successful geocoding. 

This can be done in the geocoder client but will be probably more efficient if done in the DB.

cc/ @iriberri, who can give more context if needed. Note: I've looked up for an existing issue in both repos but haven't found any.

**Comment by iriberri** [comment]
Related: https://github.com/CartoDB/data-services/issues/30

**Comment by iriberri** [comment]
will take care of this in a grouped issue
