### ISSUE TITLE
The ability to filter by Admin1 was never exposed in the Geocoder UI

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/data-services#128]
https://github.com/CartoDB/data-services/blob/master/geocoder/namedplace/geocode_namedplace.sql#L97

(['new york'], ['new york'], 'united states')
@saleiva @iriberri

**Comment by saleiva** [comment]
\0/ 
We should add an extra row to the named places georeferencing, right?

**Comment by iriberri** [comment]
Wow, Logan will be happy :)
