### ISSUE TITLE
When geocoding a dataset by city new york is placed on the middle of nowhere

### ISSUE THREAD

**Issue by jatorre** [CartoDB/data-services#129]
If you geocode a record with

city,country
New York, usa

you get a point in the middle of nowhere, attached.

It could be that there are multiple matches for New York. Geonames has a population column, we should order by population so the most populated place would have been picked.

![screen shot 2015-04-15 at 3 22 34 pm](https://cloud.githubusercontent.com/assets/127803/7167478/46c91a4c-e383-11e4-945f-c7af9de7f680.png)

**Comment by jatorre** [comment]
Hey @iriberri not sure if I need to ping you :)

**Comment by iriberri** [comment]
This is because geonames understands our New York as 'New York City' and
the New York geocoded is just another one. We'll need to overwrite that...

On Wednesday, April 15, 2015, Javier de la Torre <notifications@github.com>
wrote:

> Hey @iriberri <https://github.com/iriberri> not sure if I need to ping
> you :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/data-services/issues/129#issuecomment-93538406>
> .
>


-- 

Carla Iriberri
*CartoDB*

**Comment by jatorre** [comment]
Yeah. But here is the thinking. 

If a match is 95% like in this case, and the difference on population is dramatic, like nyc is 6m times bigger, we should pick then the big city. :)

**Comment by iriberri** [comment]
We always pick the biggest population, but 'New York' has 0 population in
the database and 'New York City' the actual one. That's why it retrieves
another New York, whose population is small but bigger than 0.

Manual change needed, I'll take care tomorrow.

On Wednesday, April 15, 2015, Javier de la Torre <notifications@github.com>
wrote:

> Yeah. But here is the thinking.
>
> If a match is 95% like in this case, and the difference on population is
> dramatic, like nyc is 6m times bigger, we should pick then the big city. :)
>
>
> > On 15/4/2015, at 15:25, Carla <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > This is because geonames understands our New York as 'New York City' and
> > the New York geocoded is just another one. We'll need to overwrite
> that...
> >
> > On Wednesday, April 15, 2015, Javier de la Torre <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > Hey @iriberri <https://github.com/iriberri> not sure if I need to ping
> > > you :)
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/CartoDB/data-services/issues/129#issuecomment-93538406>
> > > .
> > >
> >
> >
> > --
> >
> > Carla Iriberri
> > *CartoDB*
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/data-services/issues/129#issuecomment-93544393>
> .
>


-- 

Carla Iriberri
*CartoDB*

**Comment by iriberri** [comment]
Closing. Will take care of this in https://github.com/CartoDB/data-services/issues/142
