### ISSUE TITLE
Add Canadian Census data to Data Library

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/data-services#131]

**Comment by iriberri** [comment]
* [ ] http://open.canada.ca/data/en/dataset/e5d97c5d-a08a-4b0b-9cc7-2153660f7c29
* [ ] http://open.canada.ca/data/en/dataset/14f7810f-a625-4872-a1ba-9b86a6c8a2b4
* [ ] http://open.canada.ca/data/en/dataset/48f544ed-e578-436c-8460-eacb64e61a9d
* [ ] http://open.canada.ca/data/en/dataset/01c121d2-a4a3-4905-a2c9-691566ec42a8
* [ ] http://open.canada.ca/data/en/dataset/acab23c0-8936-4a8c-a1ef-13bc619390a1
* [ ] http://open.canada.ca/data/en/dataset/1644b63b-c84b-4407-ae3a-9a8bb7573f58

**Comment by saleiva** [comment]
lovely

**Comment by samueltc** [comment]
Any update on this? How can we help to get this done?

**Comment by iriberri** [comment]
No updates, unfortunately. But as I already did a small selection of some files, I'll try to upload them and publish next week, it shouldn't take too long. :-)

If you have any other specific file that you want to be uploaded, just send me the link here and I'll manage it.

Thank you for following up this issue!

**Comment by iriberri** [comment]
Done. We still need to update the public Data Library lists, but everything is set up now.

**Comment by samueltc** [comment]
They are now in the data library lists, thanks!

**Comment by iriberri** [comment]
:smile:
