### ISSUE TITLE
geocoding offset for barcelona + madrid, maybe others :(

### ISSUE THREAD

**Issue by auremoser** [CartoDB/data-services#138]
moved issue #579 from cartodb-platform to data-services.

Sometimes exports from open data portals.es geocode slightly shifted (usually up and to the left) such that lines which would normally align with the basemap roads, or polygons which would otherwise match buildings/ area footprints are off, slightly. This can be corrected in SQL, but it would be **110% rad** if it automatically reset to the appropriate projection. 

Here is an example, bike cyclelane data from Madrid ([zip here](https://www.dropbox.com/s/cooe1xgjlscrwuz/bk_mad_3_cycleway_sets%20%281%29.zip?dl=1) imports into cartodb about 50-100 meters off, so that the cyclelanes go through buildings, [source here, though the zip packages 3 datasets which when solo won't import correctly](http://datos.madrid.es/portal/site/egob/menuitem.c05c1f754a33a9fbe4b2e4b284f1a5a0/?vgnextoid=325e827b864f4410VgnVCM2000000c205a0aRCRD&vgnextchannel=374512b9ace9f310VgnVCM100000171f5a0aRCRD).

This corrects the error in the SQL tray:

`UPDATE table_name SET the_geom_webmercator = ST_Translate (the_geom_webmercator,-148,-165)`

Like this:
![screenshot 2015-05-07 20 21 48](https://cloud.githubusercontent.com/assets/1559703/7539363/bd435b30-f5a6-11e4-819e-14db2fa54928.jpg)

And here is [a bl.ock](http://bl.ocks.org/auremoser/6e984c0ff866e04686c8) that shows how it renders when corrected. I am not sure if these numbers will work for all offset datasets however. For example, [my bl.ock here](http://bl.ocks.org/auremoser/7990e895458123a20f68) is also off, but these are polygons, from Common Data (parcelas_Islas_barcelona) from [CartoBCN](http://w20.bcn.cat/cartobcn/) (another open data portal).

Like this:
![screenshot 2015-05-08 17 23 39](https://cloud.githubusercontent.com/assets/1559703/7539410/1ceea9b8-f5a7-11e4-937c-856e475fde5b.jpg)

At the very least, I guess we should correct the Common Data set so that users don't import an offset polygon series, but I suspect because this happened twice, that it's a more common problem than just one or two cases...so maybe there's a way to control for it at the platform level? 

Thank you for reading! :kiss:

**Comment by iriberri** [comment]
I have been checking the datasets that we have for Mad and Bcn and they're correct now :)

This will always happen as we're not doing lots of magic with the projection of the imported files, in the future we want to improve those things in the importer.

Closing the issue as the topics related with data-services are ok now. I'll be adding more datasets from CartoBCN soon. Thanks!

**Comment by auremoser** [comment]
Thank you!

**Comment by antosf** [comment]
Hello,
I am having the same issues with shapefiles for the Brussels Capital Region availabe from the bric.brussels (https://s.irisnet.be/v1/AUTH_ce3f7c74-fbd7-4b46-8d85-53d10d86904f/Region/UrbAdm_SHP.zip). 

As previously reported I experience a 50-100 meters off so that the districts borders are not the actual ones.

Could be possible for you to check your dataset for Brussels?

Many thanks in advance!
