### ISSUE TITLE
Improve quality of the Named Places geocoder

### ISSUE THREAD

**Issue by saleiva** [CartoDB/data-services#142]
It cannot be that we don't have things like Rome

**Comment by iriberri** [comment]
https://github.com/CartoDB/data-services/issues/134

**Comment by iriberri** [comment]
Quick trick to workaround - needs cleaning and documenting:

INSERT INTO global_cities_points_limited(the_geom, lowername, iso2, geoname_id, population, asciiname, name)  SELECT the_geom, lower(name) as lowername, iso_a2 as iso2, geonameid, pop_max as population, nameascii as asciiname, name  FROM ne_10m_populated_places_simple

**Comment by iriberri** [comment]
needs synonyms: SELECT * FROM global_cities_alternates where geoname_id = 3169070

**Comment by iriberri** [comment]
Mystery resolved: allcountries.txt has double quotes in the middle of some rows, what makes them disappear. We'll need to preprocess the source before importing.

**Comment by iriberri** [comment]
Will take care of this in a grouped issue.
