### ISSUE TITLE
geocoding offset for brussels

### ISSUE THREAD

**Issue by antosf** [CartoDB/data-services#157]
Hello!
 
like in the issue geocoding offset for barcelona + madrid, maybe others :( #138
I am having the samewith shapefiles for the Brussels Capital Region availabe from the bric.brussels (https://s.irisnet.be/v1/AUTH_ce3f7c74-fbd7-4b46-8d85-53d10d86904f/Region/UrbAdm_SHP.zip).

As previously reported I experience a 50-100 meters off so that the districts borders do not match the actual ones.

Could be possible for you to check your dataset for Brussels?

Many thanks in advance!

**Comment by iriberri** [comment]
Hi @antosf, the issue you mention was explicitly referring to two datasets that we are offering in our Data Library section. :-) I think you're experiencing the same thing with the Shapefile you attach, and the solution is to find out in which projection is the Shapefile created in order to correct it. Do you happen to know it or is there some site in which any metadata for that file is published? If not, the other trick I usually do is to open QGIS and try to test with a couple of projections of the region in which I'm interested. Let me know if you have any detail and tomorrow I'll try to help you with this (I'm working from the GMT+2 timezone!)

**Comment by antosf** [comment]
Dear Carla,

In the original zip there was also a prj file.
I paste its content below:

PROJCS["Belge_Lambert_1972",GEOGCS["GCS_Belge_1972",DATUM["D_Belge_1972",SPHEROID["International_1924",6378388.0,297.0]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["False_Easting",150000.01256],PARAMETER["False_Northing",5400088.4378],PARAMETER["Central_Meridian",4.367486666666666],PARAMETER["Standard_Parallel_1",49.8333339],PARAMETER["Standard_Parallel_2",51.16666723333333],PARAMETER["Latitude_Of_Origin",90.0],UNIT["Meter",1.0]]

Are those the metadata you are talking about?

Thanks for your prompt response!

bests

Antonio

**Comment by iriberri** [comment]
Oh, I didn't think about the .prj file. I'd open your file with QGIS, set CRS to the one specified there, and save the layer as WGS 84 EPSG 4326, then import to CartoDB. Other approach is to find the SRID number of the projection and apply the query that is available in the issue you referenced. I can help you with this tomorrow if you're not able to sort it out!

**Comment by antosf** [comment]
Thanks for your support, as you might have understood I am not that
confident with GIS and the alike...can I find the CRS written in my prj
file (or it has nothing to do with it) ?

In the meanwhile will try to figure out myself and I will let you know!

thanks!

bests

Antonio

**Comment by antosf** [comment]
Solved it with QGIS :)

Just out of curiosity, how would it be applying the query?

Via http://prj2epsg.org/search I found the SRID number (that was EPSG:31370)
but then I had no idea which values to replace in the query from the
referenced issue!

bests

Antonio

**Comment by iriberri** [comment]
Hi @antosf, glad you make it work!

Oh, sorry. We actually have the referenced issue duplicated in an internal repo in which a different query applies:

```sql
update tablename set the_geom= st_transform(st_setsrid(the_geom, 4230), 4326) 
````

In this case, you'd need to replace the 4230, as with the st_setsrid function you're saying that your geometry is in 31370 and you want to transform it to 4326. So, it would be:

```sql
update tablename set the_geom= st_transform(st_setsrid(the_geom, 4230), 4326) 
````

Hope this helps! You can close the issue if you feel everything is OK.

**Comment by antosf** [comment]
I see!
Thanks a lot for your support and your time, it was decisive!

have a nice day

Antonio

**Comment by antosf** [comment]
Ah sorry I forgot! thanks!
