### ISSUE TITLE
Add Australia administrative regions

### ISSUE THREAD

**Issue by iriberri** [CartoDB/data-services#160]
http://geoserver.nationalmap.nicta.com.au/region_map/web

info: http://www.abs.gov.au/websitedbs/D3310114.nsf/4a256353001af3ed4b2562bb00121564/c453c497aadde71cca2576d300026a38/$FILE/ASGS%202011%20Structure%20and%20Summary.pdf

**Comment by iriberri** [comment]
https://github.com/NICTA/nationalmap/wiki/csv-geo-au

**Comment by iriberri** [comment]
http://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/2033.0.55.0012011?OpenDocument

**Comment by ernesmb** [comment]
Just for future reference: 
![captura de pantalla 2015-11-06 a las 12 17 42](https://cloud.githubusercontent.com/assets/10940006/11002994/7e5b4a10-84b0-11e5-8ec1-dfebe2161c69.png)

**Comment by ernesmb** [comment]
Also adding Greater Capital City Statistical Area (GCCSA)
