### ISSUE TITLE
possibly incorrect table name for admin0 rename

### ISSUE THREAD

**Issue by gtallen1187** [CartoDB/data-services#163]
In the [**Admin0 portion**](https://github.com/CartoDB/data-services/wiki/Geocoder-Datasources#admin0-countries) of the Geocoder Datasources wiki page, there is a note that reads:

 > **Note:** Table name is being changed to ne_admin1_v3

For the admin0 portion, shouldn't this table actually be renamed to **ne_admin0_v3**?

**Comment by iriberri** [comment]
Totally, you're right. I'm updating that right now, but the wiki does not contain the updated documentation anymore. The new process we're documenting lives now in the files of the repo itself. Thanks!
