### ISSUE TITLE
syntax error on U.S. postal code polygons table creation

### ISSUE THREAD

**Issue by gtallen1187** [CartoDB/data-services#164]
very minor, but just in case it might help someone else later on, the destination column list is missing a comma between `the_geom_webmercator` and `iso3`.

```sql
INSERT INTO global_postal_code_polygons
  (the_geom, geoid10, mtfcc10, postal_code_num, zcta5ce10,  postal_code, the_geom_webmercator, iso3)
```

**Comment by iriberri** [comment]
Thanks again! As I told you in the other ticket, now everything should be managed here: https://github.com/CartoDB/data-services/tree/master/geocoder/postal-codes

I hope this documentation is more helpful than the wiki. I'll add some deprecation messages in the old wiki, as we are no longer maintaining it :-)

If you find an issue in the files of the repo, feel free to send a pull request if you want to collaborate! :smiley:
