### ISSUE TITLE
US cities are georeferenced in wrong locations

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/data-services#167]
- Try to georeference the cities selecting it the city column, setting the country to US and using points
- The Map view represent other places

![captura de pantalla 2015-09-25 a las 16 47 37](https://cloud.githubusercontent.com/assets/14546701/10103684/920bd380-63a5-11e5-91ce-8c7f10f46e3f.png)

CSV -> https://www.dropbox.com/s/26zj5txww4pg8rl/ufo_state.csv?dl=0

**Comment by rafatower** [comment]
cc/ @iriberri

**Comment by iriberri** [comment]
Hi @urbanphes,

Are you using States as extra information for the city names? If you are just using names, it's possible that the geocoder is choosing other city that is not the one of the state you want, so specifying the state is always helpful.

I'll take a look at Washington because in this case we should make sure that the one we expect is the one that appears. In principle, we use Geonames data and the cities are retrieved by the population they have

**Comment by rafatower** [comment]
@iriberri I saw the results and it doesn't mach at all with "most populated places" rule of thumb. They were obviously wrong.

**Comment by iriberri** [comment]
We don't use populated places for this, and Geonames has empty population data for some cities. This happened already with New York and I had to manually make a change in the database (and document it to be able to reproduce it).

**Comment by iriberri** [comment]
![image](https://cloud.githubusercontent.com/assets/1730320/10105478/2f858602-63af-11e5-8eff-0613fdddcf49.png)

**Comment by iriberri** [comment]
Juanma's:

                table_name                 | formatter |  state   |    kind    | country_code | processable_rows | real_rows | country_column | region_column |                                                                                                                                                       region_code                                                                                                                                                        
-------------------------------------------+-----------+----------+------------+--------------+------------------+-----------+----------------+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 ufo_2015                                  | {city}    | finished | namedplace | 'US'         |             3777 |      3211 |                | state         | 'PA','FL','AZ','LA','MT','AB','NM','AK','NC','OR','BC','NB','VT','NS','MS','AR','MB','IL','MO','IN','HI','WY','UT','MI','KS','MD','GA','WI','MN','DC','OH','NE','CT','NV','SK','OK','AL','WV','CA','DE','CO','','ND','KY','WA','ME','QC','ON','RI','PE','VA','SD','TN','NH','YT','SA','IA','SC','NY','MA','TX','NJ','ID'
 test_ufo_sheet1                           | {city}    | finished | namedplace | 'US'         |              318 |       281 |                | state         | 'PA','FL','AZ','LA','MT','AB','NC','OR','BC','VT','MS','AR','IL','MO','IN','HI','WY','UT','MI','KS','MD','GA','WI','MN','OH','NE','CT','NV','SK','OK','AL','CA','DE','CO','','WV','WA','KY','ME','QC','ON','RI','VA','SD','TN','NH','IA','SC','NY','MA','TX','NJ','ID'
 importer_1f415d46639811e583920e49835281d6 | city      | finished | namedplace |              |                3 |         0 |                |               | 
 importer_cd139ca6639611e5a1a20e5e07bb5d8a | city      | finished | namedplace |              |                3 |         0 |                |               | 
 test_ufo_sheet1                           | {city}    | finished | namedplace | 'US'         |                3 |         3 |                |               | 
 importer_e53c6200639511e5994b0e6e1df11cbf | city      | failed   | namedplace |              |                3 |           |                |               | 
 ufo_state                                 | {city}    | finished | namedplace | 'us'         |               14 |         0 |                |               | 
 ufo_state                                 | {city}    | finished | namedplace | 'us'         |               54 |        40 |                |               | 
 ufo_state                                 | {city}    | finished | namedplace | 'world'      |                  |         0 |                |               | 
 ufo_state                                 | {city}    | finished | namedplace | 'USA'        |                1 |         0 |                |               | 
 ufo_state                                 | {city}    | finished | namedplace | 'USA'        |               69 |        40 |                |               |

**Comment by iriberri** [comment]
Which means that: My first attempt and Juanma's first attempt were equivalent (40 rows as result). I'd have to analyse explicitly this result and then the results of the different approaches you've been using.

**Comment by iriberri** [comment]
Checking now the individual city names. It's true that at first sight the results seem random, but they should be appearing in cities that share the name, if not something is horribly broken. I'm creating a table with city, expected result, and insights. Will post asap.

**Comment by iriberri** [comment]
I just realised that your table does not contain City names, but States. I'm going to dig further to check if there are cities that might appear correctly that aren't, but geocoding States should be done by the Adminsitrative Regions category instead.

**Comment by iriberri** [comment]
Everything seems fine. I was confused by the results, but checked the table and the query thoroughly and everything makes sense. For Michigan, for example, it's retrieving the city in North Dakota https://en.wikipedia.org/wiki/Michigan_City,_North_Dakota.

![image](https://cloud.githubusercontent.com/assets/1730320/10198858/41571d12-679e-11e5-9df3-8821cb586bab.png)
