### ISSUE TITLE
#10511 create_the_geom_from_namedplaces_guessing failed: function namedplace_guess_country(text[]) does not exist staging · Rails

### ISSUE THREAD

**Issue by rafatower** [CartoDB/data-services#186]
In staging, some functions are missing in our extension

**Comment by rafatower** [comment]
cc/ @iriberri

**Comment by iriberri** [comment]
Oh. I see. I never thought of adding the guessing part also here, but obviously it makes no sense having it anywhere else. 

On it asap.

**Comment by rafatower** [comment]
Just forgot to mention: https://github.com/CartoDB/data-services/blob/master/geocoder/namedplace/sql/namedplace_country_guessing.sql

cause I don't simply add functions to the server :dancer:
