### ISSUE TITLE
Are we using most updated Map PLUTO Manhattan version in Data Library?

### ISSUE THREAD

**Issue by ztephm** [CartoDB/data-services#189]
@iriberri 

S/B 7394460

We have "mnmappluto" NYC MapPLUTO - Manhattan (& other boros/all) in our Data Library, but when I connect it I don't see metadata about which version we're using.

Is Release 15v1 the latest, and are we using it already? http://www.nyc.gov/html/dcp/html/bytes/dwn_pluto_mappluto.shtml

**Comment by iriberri** [comment]
The datasets were uploaded at:

````
     name     |          updated_at           
--------------+-------------------------------
 bxmappluto   | 2015-03-31 15:35:42.997793+00
 qnmappluto   | 2015-03-31 15:35:10.730356+00
 mnmappluto   | 2015-03-31 15:36:38.448681+00
 simappluto   | 2015-03-31 15:35:18.529418+00
 nycpluto_all | 2015-06-19 14:55:43.310347+00
 bkmappluto   | 2015-10-20 10:09:23.685266+00
````

So none of them, neither the `nycpluto_all` comes from the last version which seems it was published on July 20th.
