### ISSUE TITLE
cities of USA are not georeferenced if the state column has state codes 

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/data-services#191]
When you geocode by City Names option (city/Region/Country) a dataset from united states, if the column that you select for the region are the states of USA, and this column instead of the name of the state has its code, CartoDB doesn' gereference the data.
However if the state column has the name of the state, the data is georeferenced.

Steps
1- Open a dataset without geometries and with names of cities and states from United States of America. the states column should have the state code instead of the state name.
Example: 

  -City: Denver
 - State: CO
 - Country: USA 

2- Open the georeference wizard and select the georeference by "City Name" option.

3-  Select the city column, the state column for  the admin regions and write 'USA' or 'United States of America' for the country name.Click "continue"

4- The result is that any row has been georeferenced.

If you write the complete name of the state, then the rows are georeferenced for example:

  -City: Denver
 - State: Colorado
 - Country: USA

**Comment by iriberri** [comment]
Sorry, but can't reproduce:


![image](https://cloud.githubusercontent.com/assets/1730320/11375778/7e034fd2-92dd-11e5-8eff-ef0410274e76.png)

**Comment by iriberri** [comment]
By the way, FYI, there's another issue in this repo related with space cleaning on user inputs. This would have prevented the issue here.
