### ISSUE TITLE
Add recently created postal code to our system?

### ISSUE THREAD

**Issue by ztephm** [CartoDB/data-services#201]
@iriberri 

SB 7584459

I'm unable to georeference United States postal code 11249.

It was a zip code [created in 2011, from part of zip code 11211](http://www.brooklynpaper.com/stories/34/23/wb_zipcodechange_2011_06_10_bk.html). I checked the US ZCTA Cartographic Boundary Shapefile from [2014](https://www.census.gov/geo/maps-data/data/cbf/cbf_zcta.html) & it looks like there's only 11211, but I know ZCTA's are slightly different from zip codes anyway. Is the 2014 US ZCTA Cartographic Boundary Shapefile what our system is using? Is there a way to update our geocoder to include 11249?

Ref: http://bit.ly/1lN2ZuH

**Comment by iriberri** [comment]
For our postal code geocoder we have TIGER 2013 ZCTAs (tl_2013_us_zcta510) (http://www2.census.gov/geo/tiger/TIGER2013/ZCTA5/).

"ZIP Code Tabulation Areas (ZCTAs) are generalized areal representations of United States Postal Service (USPS) ZIP Code service areas.

The USPS ZIP Codes identify the individual post office or metropolitan area delivery station associated with mailing addresses. USPS ZIP Codes are not areal features but a collection of mail delivery routes."

If it's not in the files offered by the US Census I don't think we can add this one.

**Comment by ztephm** [comment]
ok thank u @iriberri, closing.
