### ISSUE TITLE
GeoJSON Field Guessing - Numbers as Strings when there are Null values

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/data-services#208]
S/B 8104974
@iriberri 

### Context
Number values not correctly guessed in GeoJSON value when some of the values are null

### Process
Import a GeoJSON file where one of the objects has null values in the number columns
The columns with number values will sometimes be guessed as string, sometime as number

### Expected Result
Null columns that are number values should be guessed as type number

###  Current Result
![screen shot 2016-02-11 at 11 09 27 am](https://cloud.githubusercontent.com/assets/5423288/12981741/f605b87a-d0af-11e5-9547-d915c493b385.png)

Example geojson:

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
          "name": "Dinagat Islands",
          "test1": 1234,
          "test2": 56789.5,
          "test3": 23456,
          "test4": 229494.5,
          "test5": 407.5,
          "test6": 52341,
          "test7": 6494.5,
          "test8": 12345
      },
      "geometry": {
        "type": "Point",
        "coordinates": [125.6, 10.1]
      }
    },
    {
      "type": "Feature",
      "properties": {
          "name": "Dinagat Islands",
          "test1": null,
          "test2": null,
          "test3": null,
          "test4": null,
          "test5": null,
          "test6": null,
          "test7": null,
          "test8": null
      },
      "geometry": {
        "type": "Point",
        "coordinates": [-125.6, 10.1]
      }
    }
  ]
}
```

**Comment by iriberri** [comment]
@michellechandra could you please move this issue to the `cartodb` repo? This one is oriented to the Geocoding extension and common data metadata.

**Comment by michellechandra** [comment]
https://github.com/CartoDB/cartodb/issues/6572
