### ISSUE TITLE
Geocoding France polygon does not include 'Corsica'

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/data-services#213]
When we use the geocoding functions to get the France polygon, it does not include the Corsica region nor any other [non-continental regions of France](https://en.wikipedia.org/wiki/France#/media/File:Outre-mer_en_sans_Terre_Adelie.png). 

## Steps to reproduce
- Use geocoding function to get France admin0 polygon: 
`SELECT ST_Transform(cdb_geocode_admin0_polygon('FRA'), 3857) AS the_geom_webmercator` 
- Or try to geocode a table containing `France` or `FRA`

## Expected result
The returned polygon should include 'Corsica' and the other islands, as the `world_borders_hd` and `world_borders` datasets do:
![screen shot 2016-03-08 at 17 46 17](https://cloud.githubusercontent.com/assets/10940006/13610090/5916aa30-e55c-11e5-97f8-7782de46545e.png)

## Current result
The returned polygon does not include 'Corsica' or any other peripheral french region
![screen shot 2016-03-08 at 17 45 26](https://cloud.githubusercontent.com/assets/10940006/13610104/69fe83d6-e55c-11e5-9d21-6d51fe562945.png)

**Comment by rafatower** [comment]
Totally debatable when it should include Corsica, La Réunion or any other overseas departments.

**Comment by rafatower** [comment]
FYI: it was already changed to exclude them

**Comment by iriberri** [comment]
Yes, this is on purpose.

**Comment by iriberri** [comment]
https://github.com/CartoDB/data-services/blob/master/geocoder/admin0/sql/subdivide_polygons.sql

**Comment by ernesmb** [comment]
I see, thanks for clarifying :)
