### ISSUE TITLE
iso codes don't georeference consistently

### ISSUE THREAD

**Issue by ztephm** [CartoDB/data-services#214]
Hi @iriberri can you help with this or please re-assign? Thanks!

S/B 8621784

## Context
Dataset contains column of ISO3 codes. When importing and syncing same codes, sometimes they georeference, sometimes they fail.

## Process
1. Create hourly sync-table with type & content-guessing box checked from [this GDrive file](https://drive.google.com/file/d/0Bw0ywRFon5y5a3luZ3pvcjJTcVU/view?usp=sharing)
2. Create hourly sync-table with type & content-guessing box checked from [this GDrive file](https://drive.google.com/file/d/0Bw0ywRFon5y5M0hrQk5yRzMyWnc/view?usp=sharing) too 

## Expected result
They should both be automatically georeferenced the same way, since they contain the same ISO codes. 

## Current result
Here's [first one:](https://team.cartodb.com/u/stephaniemongon/tables/iso_only_1to10)

![success_1to10](https://cloud.githubusercontent.com/assets/1779444/15193576/893cf662-178c-11e6-891f-8eaba0ef59fa.png)

Here's [second one:](https://team.cartodb.com/u/stephaniemongon/tables/iso_only_1to11)

![fail_1to11](https://cloud.githubusercontent.com/assets/1779444/15193601/a86e907c-178c-11e6-86d8-c49e6255a796.png)

Anything we can do to make sure they always georeference properly?

**Comment by iriberri** [comment]
Even though the CartoDB internal geocoder lives here, this issue is related with data guessing. I moved it to https://github.com/CartoDB/cartodb/issues/7386, let's talk there!
