### ISSUE TITLE
Country Name Geocoding: Add Additional Name, Republic of the Congo

### ISSUE THREAD

**Issue by rafatower** [CartoDB/data-services#216]
@michellechandra commented on [Mon Jun 20 2016](https://github.com/CartoDB/cartodb/issues/7960)

## Context
A user with government datasets is having difficulties manually geocoding a dataset by country names as the dataset uses "Republic of **the** Congo" while the geocoder recognizes: 

_Republic of Congo,COG,Congo,CG_

Would it be possible to add an additional alias to the geocoder to also recognize "Republic of the Congo" as a valid country name option for Congo?

S/B: 9219427

**Comment by iriberri** [comment]
I'm editing the message because it could cause confusion. Democratic Republic of the Congo is not the same administrative region as Republic of (the) Congo.
