### ISSUE TITLE
Add Eswatini as synonym of Swaziland

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/data-services#243]
Requested by SB/19231460

Since April 19 April 2018, Swaziland has a new official name: `eSwatini` or `Kingdom of Eswatini`. We need to add these common names to our internal geocoder.

**Comment by ramiroaznar** [comment]
@ethervoid let me know if you want me to give you the acceptance for this one.

**Comment by ethervoid** [comment]
Merged and updating this patch in the production servers

**Comment by ramiroaznar** [comment]
Cool. Contacting our client. Feel free to close this one as soon as this is on production.

**Comment by ethervoid** [comment]
Deployed in production
