### ISSUE TITLE
Name simplification regex

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/data-services#30]
I am doing a simplification of name texts via this regex,

```
lower(regexp_replace(NEW.name, '[^A-z\u00C0-\u00ff]+', '', 'g'));
```

it helps remove fluff that could easily be variable across user data. For example, spaces and hyphens '-'. I'm also allowing accented characters (some, latin1) but not all. 
It would be handy if there was a more dummy regex we could use that would turn say,

España into espana. That sort of character swap would probably be even more useful, because then if I had crap data that just said Espana it would match against the same result as your data that says, España. I can easily store two rows here in the synonyms table, but think it is probably cleaner if we just do it this way. 

Got any expertise here?

background

You can see it in the automated trigger that populates the ```name_``` column,

https://github.com/CartoDB/data-services/wiki/Indexes-and-triggers

and it is used again to then transform a user entry to match against that column here,

https://github.com/CartoDB/data-services/blob/master/geocoder/admin0/sql/geocoder.sql#L17

**Comment by javisantana** [comment]
we should do as much as possible in postgres side, also we have nice extensions for this: http://www.postgresql.org/docs/9.3/static/unaccent.html
