### ISSUE TITLE
Update postal code source

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/data-services#47]
https://github.com/CartoDB/cartodb/blob/master/app/controllers/api/json/geocodings_controller.rb#L49

cc/ @rilla

**Comment by iriberri** [comment]
This was edited a long time ago. The first link should be https://github.com/CartoDB/cartodb/blob/2264fcff65806d8c960075e1e7b814dfd15806d2/app/controllers/api/json/geocodings_controller.rb#L49 and we are no longer using that old method. Closing.
